# use OpenJDK as base image
FROM openjdk:17

#copy application JAR

COPY target/SpringBoot_JDBC_Template-0.0.1-SNAPSHOT.jar app.jar

# expose the port
EXPOSE 8080

#run the application
ENTRYPOINT ["java","-jar","/app.jar"]